<a href="https://colab.research.google.com/github/AlbertoMartinezS/idal_ia3/blob/main/RepasoKeras_APIFuncional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Keras

Keras es una librería construída para el prototipado rápido de modelos de deep learning. Las ventajas de Keras frente a otros frameworks de deep learning son obvios:

- Rápido prototipado (entrenamiento y evaluación) de modelos de deep learning.

- Posee una api sencilla con la que se pueden añadir estructuras complejas en redes de neuronas (capas).

- Se integra con las herramientas de tensorflow de forma nativa.

Keras permite construir modelos utilizando diferentes tipos de api (Application Porgram Interface). Las distintas apis tienen sus ventajas e inconvenientes, en esta clase vamos a estudiar la api secuencial y la api funcional de Keras.

# Keras Sequential API

La api secuencial de Keras permite construir modelos añadiendo capas en forma de secuencia. Su uso es muy directo siguiendo los siguientes pasos:

- Definimos el modelo utilizando la clase Sequential.

- Añadimos capas al modelo utilizando el método .add()

- Comppilamos el modelo utilizando el método .compile()

In [38]:
import tensorflow.keras as keras
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split

In [39]:
# Ejemplo
dataset = sns.load_dataset("iris")
model = keras.models.Sequential()
layer_1 = keras.layers.Dense(10, activation="relu")
output = keras.layers.Dense(3, activation="softmax")
model.add(layer_1)
model.add(output)
model.compile(optimizer="adam", loss="categorical_crossentropy")

In [40]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1:]
Y_dummies = pd.get_dummies(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y_dummies)

In [6]:
model.fit(X_train, Y_train, epochs=300)

Epoch 1/300
4/4 [==============================] - 1s 3ms/step - loss: 3.9958
Epoch 2/300
4/4 [==============================] - 0s 3ms/step - loss: 3.8156
Epoch 3/300
4/4 [==============================] - 0s 3ms/step - loss: 3.6427
Epoch 4/300
4/4 [==============================] - 0s 3ms/step - loss: 3.4922
Epoch 5/300
4/4 [==============================] - 0s 4ms/step - loss: 3.3412
Epoch 6/300
4/4 [==============================] - 0s 3ms/step - loss: 3.1922
Epoch 7/300
4/4 [==============================] - 0s 3ms/step - loss: 3.0548
Epoch 8/300
4/4 [==============================] - 0s 3ms/step - loss: 2.9206
Epoch 9/300
4/4 [==============================] - 0s 3ms/step - loss: 2.7899
Epoch 10/300
4/4 [==============================] - 0s 3ms/step - loss: 2.6614
Epoch 11/300
4/4 [==============================] - 0s 3ms/step - loss: 2.5307
Epoch 12/300
4/4 [==============================] - 0s 3ms/step - loss: 2.4141
Epoch 13/300
4/4 [==============================] - 0s 3ms/st

In [7]:
# Realizar predicción
model.predict(X_test)

array([[9.69566643e-01, 3.01268212e-02, 3.06529662e-04],
       [1.53827574e-03, 4.55660373e-01, 5.42801321e-01],
       [9.73981202e-01, 2.58070454e-02, 2.11788851e-04],
       [9.76755321e-01, 2.30145659e-02, 2.30100661e-04],
       [9.54310536e-01, 4.52266112e-02, 4.62881988e-04],
       [1.78075815e-03, 3.53589505e-01, 6.44629717e-01],
       [1.24528212e-02, 7.84019411e-01, 2.03527778e-01],
       [3.54209505e-02, 8.19233596e-01, 1.45345405e-01],
       [6.89432898e-04, 2.31733114e-01, 7.67577410e-01],
       [1.29426175e-04, 1.10174641e-01, 8.89696002e-01],
       [9.61248398e-01, 3.82420607e-02, 5.09525591e-04],
       [9.88562703e-01, 1.13794478e-02, 5.79186199e-05],
       [2.75260507e-04, 1.70294404e-01, 8.29430342e-01],
       [1.13413725e-02, 6.79447114e-01, 3.09211582e-01],
       [2.60006674e-02, 8.50874364e-01, 1.23124950e-01],
       [8.41578512e-05, 1.35597438e-01, 8.64318430e-01],
       [3.74861644e-03, 5.37801921e-01, 4.58449453e-01],
       [3.48816961e-02, 7.84299

# Ejercicio

Entrenad un modelo de 3 capas densas utilizando la api secuencial de Keras para el dataset penguins. El objetivo es clasificar el sexo del pingüino.

# Eliminar capas de un modelo secuencial.

Es posible eliminar capas de un modelo secuencial utilizando el método .pop()

In [16]:
model.layers

In [8]:
model.layers[0].weights[0].numpy()

array([[ 0.268757  , -0.07465823, -0.22026749,  0.53759927,  0.37245414,
         0.48934823,  0.27408725, -0.39633223,  0.6410071 , -0.47668225],
       [ 0.49245527, -0.4072816 ,  0.43625954,  0.10402677,  0.5564022 ,
         0.5228724 ,  0.61374885,  0.4627278 ,  0.05883714, -0.21233872],
       [ 0.3993386 ,  1.0899862 , -0.0020981 , -0.10075286, -0.71568024,
         0.1071059 ,  0.1885141 , -0.59704363, -0.42638236, -0.52437407],
       [-0.72705877,  0.47417563,  0.6370399 ,  0.14177269, -0.71405613,
         0.04354649, -0.5342403 , -0.45545578, -0.4096617 ,  0.58885384]],
      dtype=float32)

In [10]:
model.pop() #borra la última capa

In [11]:
model.layers

In [13]:
model.compile(optimizer='adam', loss= 'categorical_crossentropy')

In [17]:
model.predict(X_train).shape

array([[3.8835788 , 4.5329747 , 0.6742804 , ..., 0.        , 1.7182117 ,
        0.        ],
       [3.7563624 , 4.835718  , 0.84769845, ..., 0.        , 1.2714657 ,
        0.        ],
       [3.522902  , 0.12641358, 0.16684526, ..., 0.        , 2.8427567 ,
        0.        ],
       ...,
       [4.00368   , 4.6586504 , 0.89284563, ..., 0.        , 1.3941839 ,
        0.        ],
       [4.028231  , 4.6785336 , 0.6125331 , ..., 0.        , 1.5225655 ,
        0.        ],
       [4.882481  , 6.4445353 , 0.5331633 , ..., 0.        , 1.772085  ,
        0.        ]], dtype=float32)

In [15]:
len(model.layers)

1

In [48]:
datasetP= sns.load_dataset("penguins")
datasetP.head()
datasetP.dropna(inplace=True)

In [51]:
model = keras.models.Sequential()

layer_1 = keras.layers.Dense(128, activation= 'relu')
layer_2 = keras.layers.Dense(64, activation="relu")
layer_3 = keras.layers.Dense(32, activation='relu')
output = keras.layers.Dense(2, activation="softmax")

model.add(layer_1)
model.add(layer_2)
model.add(layer_3)
model.add(output)
model.compile(optimizer="adam", loss="categorical_crossentropy")

In [52]:
X = pd.get_dummies(datasetP.iloc[:,:-1])
Y = pd.get_dummies(datasetP.iloc[:,-1:])


X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

In [53]:
model.fit(X_train, Y_train, epochs=300)

Epoch 1/300
8/8 [==============================] - 0s 2ms/step - loss: 85.8975
Epoch 2/300
8/8 [==============================] - 0s 2ms/step - loss: 11.8969
Epoch 3/300
8/8 [==============================] - 0s 4ms/step - loss: 9.4981
Epoch 4/300
8/8 [==============================] - 0s 2ms/step - loss: 12.5265
Epoch 5/300
8/8 [==============================] - 0s 2ms/step - loss: 7.5494
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 8.6147
Epoch 7/300
8/8 [==============================] - 0s 2ms/step - loss: 8.1119
Epoch 8/300
8/8 [==============================] - 0s 2ms/step - loss: 6.0862
Epoch 9/300
8/8 [==============================] - 0s 3ms/step - loss: 5.0618
Epoch 10/300
8/8 [==============================] - 0s 3ms/step - loss: 3.7833
Epoch 11/300
8/8 [==============================] - 0s 2ms/step - loss: 2.5612
Epoch 12/300
8/8 [==============================] - 0s 2ms/step - loss: 1.6555
Epoch 13/300
8/8 [==============================] - 0s 2ms

In [54]:
model.predict(X_test)

array([[0.7517924 , 0.24820769],
       [0.9220734 , 0.07792659],
       [0.98093307, 0.01906688],
       [0.7606024 , 0.23939763],
       [0.21727328, 0.7827267 ],
       [0.71142346, 0.28857654],
       [0.77580696, 0.22419311],
       [0.46508852, 0.53491145],
       [0.07448974, 0.9255102 ],
       [0.8445808 , 0.15541917],
       [0.5509719 , 0.4490281 ],
       [0.9367967 , 0.0632033 ],
       [0.52470815, 0.47529182],
       [0.06503656, 0.93496346],
       [0.4427266 , 0.5572734 ],
       [0.46700838, 0.5329915 ],
       [0.7464333 , 0.25356668],
       [0.78499293, 0.21500707],
       [0.9708322 , 0.02916779],
       [0.5012684 , 0.49873164],
       [0.51167136, 0.4883287 ],
       [0.72644377, 0.27355617],
       [0.5815106 , 0.41848943],
       [0.6117689 , 0.3882311 ],
       [0.8427533 , 0.15724663],
       [0.953781  , 0.04621901],
       [0.84941006, 0.15058996],
       [0.27462372, 0.72537625],
       [0.9772183 , 0.02278175],
       [0.41408253, 0.5859174 ],
       [0.

In [62]:
model.layers

In [ ]:
model.pop()

In [ ]:
model.layers

In [63]:
model.compile(optimizer="adam", loss="categorical_crossentropy")

In [64]:
model.predict(X_test)

array([[  0.      ,  74.087906,   0.      , ...,   0.      ,  81.20981 ,
          0.      ],
       [  0.      ,  64.94846 ,   0.      , ...,   0.      ,  72.891655,
          0.      ],
       [  0.      ,  63.743534,   0.      , ...,   0.      ,  72.31753 ,
          0.      ],
       ...,
       [  0.      ,  86.972336,   0.      , ...,   0.      ,  94.8155  ,
          0.      ],
       [  0.      ,  68.20113 ,   0.      , ...,   0.      ,  75.97235 ,
          0.      ],
       [  0.      , 126.732544,   0.      , ...,   0.      , 132.01147 ,
          0.      ]], dtype=float32)

# API Funcional

La api funcional de Keras plantea construir un modelo mediante funciones. Las capas definidas en esta api se estructuran como funciones de Python cuya entrada es la salida de la capa anterior. Para construir un modelo utilizando la API Funcional de Keras hay que seguir los siguientes pasos:

- Definir la entrada con keras.layers.Input()
- Definir las capas de keras.layers
- Definir el modelo con keras.models.Model()
- Compilar el modelo

In [65]:
dataset = sns.load_dataset("iris")

In [66]:
input_layer = keras.layers.Input(shape=(4,))
layer_1 = keras.layers.Dense(5, activation="relu")(input_layer)
output = keras.layers.Dense(3, activation="softmax")(layer_1)
model = keras.Model(inputs=input_layer, outputs=output)
model.compile(optimizer="adam", loss="categorical_crossentropy")

In [67]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1:]
Y_dummies = pd.get_dummies(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y_dummies)

In [68]:
model.fit(X_train,Y_train, epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 3ms/step - loss: 2.5297
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 2.4709
Epoch 3/200
4/4 [==============================] - 0s 3ms/step - loss: 2.4138
Epoch 4/200
4/4 [==============================] - 0s 4ms/step - loss: 2.3560
Epoch 5/200
4/4 [==============================] - 0s 3ms/step - loss: 2.3005
Epoch 6/200
4/4 [==============================] - 0s 4ms/step - loss: 2.2477
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 2.1968
Epoch 8/200
4/4 [==============================] - 0s 4ms/step - loss: 2.1469
Epoch 9/200
4/4 [==============================] - 0s 3ms/step - loss: 2.0988
Epoch 10/200
4/4 [==============================] - 0s 4ms/step - loss: 2.0543
Epoch 11/200
4/4 [==============================] - 0s 4ms/step - loss: 2.0110
Epoch 12/200
4/4 [==============================] - 0s 4ms/step - loss: 1.9702
Epoch 13/200
4/4 [==============================] - 0s 5ms/st

In [69]:
model.predict(X_test)

array([[0.02410651, 0.3835519 , 0.59234154],
       [0.03715771, 0.46360543, 0.4992368 ],
       [0.8144341 , 0.06796033, 0.11760552],
       [0.01534274, 0.41557944, 0.5690778 ],
       [0.00185869, 0.44262612, 0.55551517],
       [0.01684719, 0.4686582 , 0.5144946 ],
       [0.7533382 , 0.11106276, 0.135599  ],
       [0.7743796 , 0.09552751, 0.1300929 ],
       [0.00805134, 0.44528216, 0.54666656],
       [0.00349438, 0.4139645 , 0.5825411 ],
       [0.00216527, 0.38789898, 0.6099357 ],
       [0.00243533, 0.37794325, 0.61962146],
       [0.05912229, 0.3981682 , 0.5427095 ],
       [0.7576283 , 0.10784157, 0.13453005],
       [0.00102959, 0.34957507, 0.6493953 ],
       [0.7285903 , 0.11046963, 0.16093999],
       [0.7616546 , 0.10484307, 0.1335023 ],
       [0.00292743, 0.36407322, 0.63299936],
       [0.7622004 , 0.09972266, 0.13807692],
       [0.0017433 , 0.40779993, 0.5904568 ],
       [0.0045531 , 0.41951272, 0.5759342 ],
       [0.01173468, 0.4477932 , 0.54047215],
       [0.

# Acceder a las capas intermedias de un modelo

A veces es interesante poder acceder a la salida de una capa intermedia de un modelo entrenado previamente. Para ello es necesario construir un nuevo modelo definiendo una nueva salida.

Una vez definida la nueva salida es posible aplicar análisis dimensional (comprobar las dimensiones de la salida) para comprender más acerca del modelo y si hemos elegido la capa correcta.

In [70]:
new_output = model.layers[1]
model_2 = keras.Model(inputs=input_layer, outputs=new_output.output)
model_2.compile(optimizer="adam", loss="categorical_crossentropy")

In [71]:
model.layers[1]

In [ ]:
model_2.predict(X_test).shape

(38, 5)

# Ejercicio

Generad nuevos modelos que tengan como salida las capas intermedias de vuestro modelo funcional anterior. Realizad análisis dimensional sobre las salidas de las capas anteriores y comprobad si son las dimensiones correctas de esa capa.